{ defaultPackage }:
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.nm-vpngate;

  # Quote a value as a single-quoted bash string. Safe for arbitrary content
  # because the conf file is sourced by bash and we do not want shell
  # expansion of user-supplied values.
  shQuote =
    v:
    let
      s =
        if builtins.isBool v then
          (if v then "true" else "false")
        else if builtins.isInt v then
          toString v
        else
          toString v;
    in
    "'" + builtins.replaceStrings [ "'" ] [ "'\\''" ] s + "'";

  # Settings derived from the high-level options. Order matters because the
  # conf file is sourced and later assignments win; user-provided `settings`
  # are written after these so they can override.
  derivedSettings = lib.filterAttrs (_: v: v != null && v != [ ]) {
    VPN_TYPE = cfg.vpnType;
    TargetCountryShort = if cfg.country == null then null else "^${cfg.country}$";
    VPN_DNS = lib.concatStringsSep " " cfg.dns;
    USERNAME = cfg.username;
    PASSWORD = cfg.password;
    IPSEC_PSK = cfg.ipsecPsk;
  };

  allSettings = derivedSettings // cfg.settings;

  configFile = pkgs.writeText "nm-vpngate.conf" (
    "# Generated by services.nm-vpngate — do not edit\n"
    + lib.concatStringsSep "\n" (
      lib.mapAttrsToList (name: value: "${name}=${shQuote value}") allSettings
    )
    + lib.optionalString (cfg.extraConfig != "") ("\n" + cfg.extraConfig)
    + "\n"
  );
in
{
  options.services.nm-vpngate = {
    enable = lib.mkEnableOption "nm-vpngate (VPN Gate client for NetworkManager)";

    package = lib.mkOption {
      type = lib.types.package;
      default = defaultPackage pkgs;
      defaultText = lib.literalExpression "nm-vpngate.packages.\${system}.default";
      description = "The nm-vpngate package to use.";
    };

    autoConnect = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to register a systemd service that automatically connects to
        a VPN Gate server matching the configuration after network-online.target.
        When false, the package is still installed and the conf file written,
        but the connection must be triggered manually.
      '';
    };

    retryLimit = lib.mkOption {
      type = lib.types.ints.unsigned;
      default = 5;
      description = ''
        Number of connection retry attempts in auto mode (the -l flag).
        0 disables the limit.
      '';
    };

    vpnType = lib.mkOption {
      type = lib.types.enum [
        "OPENVPN"
        "L2TP"
      ];
      default = "OPENVPN";
      description = ''
        VPN protocol to use. The matching NetworkManager VPN plugin
        (networkmanager-openvpn or networkmanager-l2tp) is enabled
        automatically when this module is enabled.
      '';
    };

    country = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "JP";
      description = ''
        Restrict server selection to a country (CountryShort field). The value
        is wrapped in `^...$` and stored as TargetCountryShort. Use a regex
        like `JP|US` to match multiple countries.
      '';
    };

    dns = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [
        "1.1.1.1"
        "8.8.8.8"
      ];
      description = ''
        DNS servers to force on the VPN profile while the tunnel is active
        (sets VPN_DNS). Useful on networks where the local DNS is unreachable
        from inside the VPN tunnel. Empty list keeps whatever the VPN server
        pushes (or the prior resolver if nothing is pushed).
      '';
    };

    username = lib.mkOption {
      type = lib.types.str;
      default = "vpn";
      description = "VPN username (VPN Gate uses \"vpn\").";
    };

    password = lib.mkOption {
      type = lib.types.str;
      default = "vpn";
      description = ''
        VPN password (VPN Gate uses "vpn"). Note: this value is written to
        /etc/nm-vpngate.conf which is world-readable by default; do not put a
        sensitive secret here.
      '';
    };

    ipsecPsk = lib.mkOption {
      type = lib.types.str;
      default = "vpn";
      description = ''
        IPsec pre-shared key used when vpnType = "L2TP". VPN Gate uses "vpn".
      '';
    };

    settings = lib.mkOption {
      type = lib.types.attrsOf (
        lib.types.oneOf [
          lib.types.str
          lib.types.int
          lib.types.bool
        ]
      );
      default = { };
      example = lib.literalExpression ''
        {
          MODE = "AUTO";
          AUTO_TARGET = "Score";
          AUTO_COND = "MAX";
          KEEP_CACHE = 43200;
          USE_CACHE = true;
        }
      '';
      description = ''
        Free-form key/value entries written to /etc/nm-vpngate.conf. These are
        emitted after the high-level options so they take precedence (later
        assignments win when bash sources the file).
      '';
    };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      example = ''
        TargetHostName="public-vpn-1[0-9]{2}"
        FIX_OPENVPN_CONFIG=("cipher")
      '';
      description = ''
        Extra shell snippet appended verbatim to /etc/nm-vpngate.conf for
        settings that cannot be expressed via `settings` (such as bash array
        assignments).
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = config.networking.networkmanager.enable;
        message = ''
          services.nm-vpngate requires NetworkManager. Set
          `networking.networkmanager.enable = true;`.
        '';
      }
    ];

    environment.systemPackages = [ cfg.package ];

    networking.networkmanager.plugins =
      lib.optional (cfg.vpnType == "OPENVPN") pkgs.networkmanager-openvpn
      ++ lib.optional (cfg.vpnType == "L2TP") pkgs.networkmanager-l2tp;

    environment.etc."nm-vpngate.conf".source = configFile;

    systemd.services.nm-vpngate = lib.mkIf cfg.autoConnect {
      description = "Automatically connect to a VPN Gate server (nm-vpngate)";
      after = [
        "network-online.target"
        "NetworkManager.service"
      ];
      wants = [ "network-online.target" ];
      requires = [ "NetworkManager.service" ];
      wantedBy = [ "multi-user.target" ];

      serviceConfig = {
        Type = "oneshot";
        ExecStart = "${lib.getExe cfg.package} -a -l ${toString cfg.retryLimit}";
        ExecStop = "${lib.getExe cfg.package} --stop";
        RemainAfterExit = true;
        Restart = "on-failure";
        RestartSec = 30;
      };
    };
  };
}
